Spring 3 hw 37
YuraBondarenko/Spring-Framework pull request #3
Opened 2021-02-10 14:30 UTC by YuraBondarenko

2021-02-10 19:15 UTC, antoniukivan approved these changes

2021-02-11 08:57 UTC, Sofasmile requested changes

2021-02-11 08:57 UTC, Sofasmile commented on src/main/java/spring/controllers/UserController.java
> +    public UserResponseDto get(@PathVariable(name = "userId") Long id) {
name = "userId" is optional here

2021-02-11 08:57 UTC, Sofasmile commented on src/main/java/spring/service/UserMapperImpl.java
> +    private final UserService userService;
where do we use userService here?

2021-02-11 10:26 UTC, Sofasmile requested changes

2021-02-11 10:26 UTC, Sofasmile commented on src/main/java/spring/dao/UserDaoImpl.java
> +            return Optional.of(session.get(User.class, id));
What will the session return if the user is absent?

2021-02-11 11:41 UTC, Sofasmile approved these changes

2021-02-11 14:50 UTC, merged